import type { Listing } from "./types"

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Vintage Record Player",
    description:
      "Fully functional vintage record player from the 1970s. Great condition with minor cosmetic wear. Perfect for vinyl enthusiasts.",
    category: "Electronics",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Record+Player",
    condition: "Good",
    lookingFor: "Mountain bike or professional camera equipment",
    location: "Portland, OR",
    exchangeMethod: "In-person only",
    createdAt: "2025-03-15",
    userName: "Alex Johnson",
    userAvatar: "/placeholder.svg?height=50&width=50&text=AJ",
  },
  {
    id: "2",
    title: "Professional Photography Services",
    description:
      "Offering 2-hour professional photography session. I specialize in portraits, events, and product photography.",
    category: "Services",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Photography",
    condition: "Not Applicable",
    lookingFor: "Home repair services or high-end kitchen appliances",
    location: "Seattle, WA",
    exchangeMethod: "In-person only",
    createdAt: "2025-03-18",
    userName: "Maya Williams",
    userAvatar: "/placeholder.svg?height=50&width=50&text=MW",
  },
  {
    id: "3",
    title: "Handcrafted Wooden Dining Table",
    description:
      'Beautiful solid oak dining table handcrafted by me. Seats 6 people comfortably. 72" x 36" dimensions.',
    category: "Furniture",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Dining+Table",
    condition: "Like New",
    lookingFor: "Outdoor patio furniture or professional lawn equipment",
    location: "Austin, TX",
    exchangeMethod: "In-person only",
    createdAt: "2025-03-20",
    userName: "Carlos Rodriguez",
    userAvatar: "/placeholder.svg?height=50&width=50&text=CR",
  },
  {
    id: "4",
    title: "iPhone 13 Pro - 256GB",
    description:
      "iPhone 13 Pro in excellent condition. 256GB storage, battery health at 92%. Includes original box, charger, and two cases.",
    category: "Electronics",
    imageUrl: "/placeholder.svg?height=300&width=400&text=iPhone",
    condition: "Good",
    lookingFor: "MacBook Air or iPad Pro",
    location: "Chicago, IL",
    exchangeMethod: "Both options",
    createdAt: "2025-03-22",
    userName: "Priya Patel",
    userAvatar: "/placeholder.svg?height=50&width=50&text=PP",
  },
  {
    id: "5",
    title: "Graphic Design Services",
    description:
      "Professional graphic designer offering logo design, branding, or marketing materials. 10+ years of experience working with small businesses.",
    category: "Services",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Graphic+Design",
    condition: "Not Applicable",
    lookingFor: "High-end laptop or professional camera equipment",
    location: "New York, NY",
    exchangeMethod: "Shipping only",
    createdAt: "2025-03-25",
    userName: "David Kim",
    userAvatar: "/placeholder.svg?height=50&width=50&text=DK",
  },
  {
    id: "6",
    title: "Mountain Bike - Trek Marlin 7",
    description:
      "2023 Trek Marlin 7 mountain bike. Size medium. Ridden less than 100 miles, in excellent condition. Hydraulic disc brakes, 1x12 drivetrain.",
    category: "Sports",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Mountain+Bike",
    condition: "Like New",
    lookingFor: "Road bike or high-end camping gear",
    location: "Denver, CO",
    exchangeMethod: "In-person only",
    createdAt: "2025-03-28",
    userName: "Sarah Miller",
    userAvatar: "/placeholder.svg?height=50&width=50&text=SM",
  },
  {
    id: "7",
    title: "Leather Sofa - Brown",
    description:
      "Genuine leather sofa in rich brown color. 3-seater, very comfortable. Minor wear but in great condition. From a pet-free, smoke-free home.",
    category: "Furniture",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Leather+Sofa",
    condition: "Good",
    lookingFor: "Dining table set or bedroom furniture",
    location: "Atlanta, GA",
    exchangeMethod: "In-person only",
    createdAt: "2025-03-30",
    userName: "James Wilson",
    userAvatar: "/placeholder.svg?height=50&width=50&text=JW",
  },
  {
    id: "8",
    title: "Programming Tutoring - Web Development",
    description:
      "Offering 10 hours of one-on-one web development tutoring. I specialize in React, Next.js, and full-stack JavaScript development.",
    category: "Services",
    imageUrl: "/placeholder.svg?height=300&width=400&text=Web+Development",
    condition: "Not Applicable",
    lookingFor: "Gaming laptop or high-end desktop computer",
    location: "San Francisco, CA",
    exchangeMethod: "Both options",
    createdAt: "2025-04-02",
    userName: "Emma Chen",
    userAvatar: "/placeholder.svg?height=50&width=50&text=EC",
  },
]

import type { Conversation } from "./types"

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-1",
    participantName: "Alex Johnson",
    participantAvatar: "/placeholder.svg?height=50&width=50&text=AJ",
    listingId: "1",
    listingTitle: "Vintage Record Player",
    startedAt: "2025-04-10T14:30:00Z",
    messages: [
      {
        id: "msg-1",
        senderId: "user-1",
        text: "Hi there! I'm interested in your vintage record player. Is it still available?",
        timestamp: "2025-04-10T14:30:00Z",
        isRead: true,
      },
      {
        id: "msg-2",
        senderId: "current-user",
        text: "Yes, it's still available! Are you interested in trading?",
        timestamp: "2025-04-10T14:45:00Z",
        isRead: true,
      },
      {
        id: "msg-3",
        senderId: "user-1",
        text: "Great! I have a mountain bike I could trade. It's a Trek, about 2 years old but in excellent condition.",
        timestamp: "2025-04-10T15:00:00Z",
        isRead: true,
      },
      {
        id: "msg-4",
        senderId: "current-user",
        text: "That sounds interesting! Could you send me some pictures of the bike?",
        timestamp: "2025-04-10T15:10:00Z",
        isRead: true,
      },
      {
        id: "msg-5",
        senderId: "user-1",
        text: "Sure thing! I'll take some photos and send them over shortly.",
        timestamp: "2025-04-10T15:15:00Z",
        isRead: true,
      },
    ],
  },
  {
    id: "conv-2",
    participantId: "user-2",
    participantName: "Maya Williams",
    participantAvatar: "/placeholder.svg?height=50&width=50&text=MW",
    listingId: "2",
    listingTitle: "Professional Photography Services",
    startedAt: "2025-04-09T10:15:00Z",
    messages: [
      {
        id: "msg-6",
        senderId: "current-user",
        text: "Hello Maya, I'm interested in your photography services. I need product photos for my online store.",
        timestamp: "2025-04-09T10:15:00Z",
        isRead: true,
      },
      {
        id: "msg-7",
        senderId: "user-2",
        text: "Hi there! I'd be happy to help with your product photography. What kind of products do you sell?",
        timestamp: "2025-04-09T10:30:00Z",
        isRead: true,
      },
      {
        id: "msg-8",
        senderId: "current-user",
        text: "I sell handmade jewelry. I have about 20 pieces that need professional photos.",
        timestamp: "2025-04-09T10:45:00Z",
        isRead: true,
      },
      {
        id: "msg-9",
        senderId: "user-2",
        text: "Perfect! I have experience with jewelry photography. I noticed you're looking for home repair services. I have a friend who's a licensed plumber if you need plumbing work done.",
        timestamp: "2025-04-09T11:00:00Z",
        isRead: false,
      },
    ],
  },
  {
    id: "conv-3",
    participantId: "user-3",
    participantName: "Carlos Rodriguez",
    participantAvatar: "/placeholder.svg?height=50&width=50&text=CR",
    listingId: "3",
    listingTitle: "Handcrafted Wooden Dining Table",
    startedAt: "2025-04-08T16:20:00Z",
    messages: [
      {
        id: "msg-10",
        senderId: "user-3",
        text: "Hello! I saw your listing and I have a beautiful patio set I'd like to trade for your dining table. Would you be interested?",
        timestamp: "2025-04-08T16:20:00Z",
        isRead: true,
      },
      {
        id: "msg-11",
        senderId: "current-user",
        text: "Hi Carlos! That sounds promising. What condition is the patio set in? And do you have any photos?",
        timestamp: "2025-04-08T16:35:00Z",
        isRead: true,
      },
      {
        id: "msg-12",
        senderId: "user-3",
        text: "It's in excellent condition, only used for one season. I'll send you photos right away.",
        timestamp: "2025-04-08T16:40:00Z",
        isRead: true,
      },
      {
        id: "msg-13",
        senderId: "user-3",
        text: "Here are the photos of the patio set. It includes a table and 4 chairs, all made of weather-resistant materials.",
        timestamp: "2025-04-08T16:50:00Z",
        isRead: false,
      },
    ],
  },
]
